theme = "flexoki_dark"

[editor]
line-number = "relative"
auto-format = false
rulers = [80, 100, 120]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.indent-guides]
render = true

[keys.normal]
C-x = ":reflow"
