theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
auto-format = false
rulers = [80, 100, 120]
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"
